version: '3.8'
services:
  web_server_barber:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./volumes/api-barber:/var/www/html
    container_name: web_server_barber
    environment:
      - VIRTUAL_HOST=test.limbotecnologia.com.br
      - LETSENCRYPT_HOST=test.limbotecnologia.com.br
      - LETSENCRYPT_EMAIL=nicollasacruz@gmail.com
      - VIRTUAL_PORT=7777
    depends_on:
      - php_api_barber
    networks:
      - network_api_barber
      - reverse-proxy

  php_api_barber:
    container_name: php_api_barber
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./volumes/api-barber:/var/www/html
    networks:
      - network_api_barber

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db_dino
      PMA_PORT: 3306
    ports:
      - "9008:80"
    depends_on:
      - db_api_barber
    networks:
      - network_api_barber

  db_api_barber:
    image: mariadb
    environment:
      - TZ=${TZ:-America/Sao_Paulo}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-dbpassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-api-barber}
      - MYSQL_USER=${MYSQL_USER:-dbuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-dbpassword}
    volumes:
      - ./.docker/config/mysql:/etc/mysql/conf.d
      - ./volumes/mysql/data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - network_api_barber
    
  redis_api_barber:
    image: redis:latest
    restart: unless-stopped
    networks:
      - network_api_barber
      - database

networks :
  network_api_barber:
    external: true
    name: network_api_barber
  reverse-proxy:
    external: true
    name: reverse-proxy
  database:
    external: true
