version: '3.8'
services:
  web_server_barber:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./volumes/api-barber:/var/www/html
    container_name: web_server_barber
    environment:
      - VIRTUAL_HOST=test.limbotecnologia.com.br
      - LETSENCRYPT_HOST=test.limbotecnologia.com.br
      - LETSENCRYPT_EMAIL=nicollasacruz@gmail.com
      - VIRTUAL_PORT=7777
    depends_on:
      - php_api_barber
    networks:
      - network_api_barber
      - reverse-proxy

  php_api_barber:
    container_name: php_api_barber
    build:
      context: ./php
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./volumes/api-barber:/var/www/html
    networks:
      - network_api_barber
    
  redis_api_barber:
    image: redis:latest
    restart: unless-stopped
    networks:
      - network_api_barber
      - database

networks :
  network_api_barber:
    external: true
    name: network_api_barber
  reverse-proxy:
    external: true
    name: reverse-proxy
  database:
    external: true
